version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile.api
      target: production
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    env_file:
      - ./envs/api/.env

  mobile-app:
    build:
      dockerfile: Dockerfile.mobile-app
      target: production
    ports:
      - 19006:19006
      - 6060:19006
    depends_on:
      - api
    env_file:
      - ./envs/mobile-app/.env

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
